// App Template — ESLint flat config for the whole frontend workspace.
//
// One config, one process, four packages. `pnpm lint` at src/frontend lints
// packages/ui, packages/shared, auth and main in a single pass, so there is no
// per-package config to keep in sync and no per-package script to forget.
//
// The baseline is deliberately a STARTER baseline: the recommended rule sets
// (correctness and likely-bug rules), not a stylistic-maximalist one. Layout
// and formatting are Prettier's job — `eslint-config-prettier` goes last and
// switches off every rule that would argue with it. See .prettierrc at the
// repo root.
//
// Add rules as your project grows; do not add rules you are not willing to fix.

import js from "@eslint/js";
import pluginVue from "eslint-plugin-vue";
import globals from "globals";
import ts from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default ts.config(
  // ---------------------------------------------------------------------
  // 1) What ESLint must never look at.
  // ---------------------------------------------------------------------
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/coverage/**",
      "**/.vite/**",
      // Generated by `pnpm generate:api` — regenerated, never hand-edited.
      "packages/shared/src/api-types/**",
      // Vite/vue-tsc ambient declarations.
      "**/env.d.ts",
      "**/*.d.ts",
    ],
  },

  // ---------------------------------------------------------------------
  // 2) The baseline rule sets.
  // ---------------------------------------------------------------------
  js.configs.recommended,
  ts.configs.recommended,
  pluginVue.configs["flat/essential"],

  // ---------------------------------------------------------------------
  // 3) Language setup. Browser code (SPAs and shared packages) is ESM and
  //    runs in a DOM; .vue files need vue-eslint-parser for <template> with
  //    the TypeScript parser nested inside for <script setup lang="ts">.
  // ---------------------------------------------------------------------
  {
    files: ["**/*.{js,mjs,ts,mts,vue}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        parser: ts.parser,
      },
    },
  },

  // ---------------------------------------------------------------------
  // 4) `no-undef` in TypeScript.
  //
  //    typescript-eslint switches `no-undef` off for .ts files because the
  //    compiler already does that job, and better — but its override only
  //    matches *.ts/*.mts/*.cts, so .vue SFCs with <script setup lang="ts">
  //    are left with it on. There it fires on DOM *types* that exist at
  //    compile time and not at runtime (`NotificationPermission`,
  //    `RequestInit`, …) and reports them as undefined variables. Those are
  //    false positives, so turn the rule off for .vue too and let vue-tsc
  //    (`pnpm type-check`) catch genuinely undefined names.
  // ---------------------------------------------------------------------
  {
    files: ["**/*.vue"],
    rules: {
      "no-undef": "off",
    },
  },

  // ---------------------------------------------------------------------
  // 5) Build tooling and scripts run in Node, not the browser.
  // ---------------------------------------------------------------------
  {
    files: [
      "**/*.config.{js,mjs,ts}",
      "**/vite.config.ts",
      "**/vitest.config.ts",
      "scripts/**/*.{js,mjs,ts}",
      "eslint.config.js",
    ],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },

  // ---------------------------------------------------------------------
  // 6) Project rules — the small set worth having opinions about.
  // ---------------------------------------------------------------------
  {
    rules: {
      // Unused code is a warning, not a build-stopper, and an underscore
      // prefix is the documented way to say "yes, deliberately unused".
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
      // `any` is sometimes the honest answer while you are learning a new
      // API. Flag it so it stays visible; do not block the build on it.
      "@typescript-eslint/no-explicit-any": "warn",
      // Single-word SFC names are fine here: the shared component library
      // already namespaces everything with the `App` prefix.
      "vue/multi-word-component-names": "off",
      // `console.log` left in a commit is noise; `console.warn`/`error` are
      // legitimate.
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-debugger": "warn",
    },
  },

  // ---------------------------------------------------------------------
  // 7) Tests get a longer leash: fixtures and stubs legitimately use `any`
  //    and log.
  // ---------------------------------------------------------------------
  {
    files: ["**/*.{test,spec}.{ts,mts}", "**/__tests__/**/*.{ts,mts}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-console": "off",
    },
  },

  // ---------------------------------------------------------------------
  // 8) MUST stay last: turns off everything Prettier already decides.
  // ---------------------------------------------------------------------
  prettier,
);
